#!/bin/bash
#
#  tr_aomp_common_vars: This file is sourced by all AOMP scripts
#                       that use TheRock for builds to set AOMP 
#                       environment variables. 
#
#  The bash syntax ENVNAME=${ENVNAME:-value} checks if ENVNAME is
#  already set. If not, it assigns it the value following the :-
#  So, if you preset any AOMP env vars you override the default specified here. 

AOMP_VERSION=${AOMP_VERSION:-"22.0"}
AOMP_VERSION_MOD=${AOMP_VERSION_MOD:-"5"}
AOMP_VERSION_STRING=${AOMP_VERSION_STRING:-"$AOMP_VERSION-$AOMP_VERSION_MOD"}
AOMP_MAJOR_VERSION=${AOMP_VERSION%.*}

# Set default value for ROCm install directory and the link directory.
# tr_build_aomp.sh will copy TheRock/build/dist/rocm to $AOMP_INSTALL_DIR
# and create a link from aomp to $AOMP_INSTALL_DIR.
# AOMP will be a symbolic link AOMP_INSTALL_DIR is the versioned dir name
AOMP=${TR_AOMP:-$HOME/rocm/tr-aomp}
AOMP_INSTALL_DIR=${AOMP}_${AOMP_VERSION_STRING}

# TR_AOMP_REPOS is the parent directory for TheRock and aomp repos.  
TR_AOMP_REPOS=${TR_AOMP_REPOS:-/work/$USER/git/tr-aomp}
if [ ! -d $TR_AOMP_REPOS ] ; then
  mkdir -p $TR_AOMP_REPOS
  [ $? != 0 ] && echo "ERROR: could not create $TR_AOMP_REPOS" && exit 1
fi

AOMP_VERSION_DIR=$TR_AOMP_REPOS/aomp/tr_aomp/aomp_$AOMP_VERSION_STRING
AOMP_INFO_FILE=$AOMP_VERSION_DIR/aomp_$AOMP_VERSION_STRING.info
AOMP_PATCH_DIR=$AOMP_VERSION_DIR/patches
AOMP_SUBMODS_FILE=$AOMP_VERSION_DIR/aomp_$AOMP_VERSION_STRING.submods
AOMP_BUILD_LOGS=$AOMP_VERSION_DIR/logs

# to speedup aomp build one can skip these components.
# The default will eventually be changed to 0 (NOT SKIP)
# Set these to 0 if you want a full test of TheRock build.
AOMP_SKIP_RCCL=${AOMP_SKIP_RCCL:-1}
AOMP_SKIP_MATH_LIBS=${AOMP_SKIP_MATH_LIBS:-1}
AOMP_SKIP_ML_LIBS=${AOMP_SKIP_ML_LIBS:-1}
AOMP_SKIP_COMPOSABLE_KERNEL=${AOMP_SKIP_COMPOSABLE_KERNEL:-1}

export AOMP_VERSION_STRING AOMP_VERSION AOMP_VERSION_MOD AOMP_MAJOR_VERSION AOMP AOMP_INSTALL_DIR TR_AOMP_REPOS AOMP_INIT_THEROCK_TIP AOMP_SKIP_RCCL

# Specify target GFXLIST
# gfx not currently supported by TheRock:
#   gfx900 gfx902 gfx90c gfx1031 gfx1052 gfx1053
#   gfx9-generic gfx9-4-generic gfx10-1-generic gfx10-3-generic gfx11-generic gfx12-generic
GFXLIST=${GFXLIST:-"gfx906 gfx908 gfx90a gfx942 gfx950 gfx1010 gfx1011 gfx1012 gfx1030 gfx1032 gfx1035 gfx1036 gfx1100 gfx1101 gfx1102 gfx1103 gfx1150 gfx1151 gfx1200 gfx1201"}

export GFXLIST

