#!/bin/bash
#
#  tr_aomp_common_vars: This file is sourced by all AOMP scripts
#                       that use TheRock for builds to set AOMP 
#                       environment variables. 
#
#  The bash syntax ENVNAME=${ENVNAME:-value} checks if ENVNAME is
#  already set. If not, it assigns it the value following the :-
#  So, if you preset any AOMP env vars you override the default specified here. 

AOMP_VERSION=${AOMP_VERSION:-"22.0"}
AOMP_VERSION_MOD=${AOMP_VERSION_MOD:-"4"}
AOMP_VERSION_STRING=${AOMP_VERSION_STRING:-"$AOMP_VERSION-$AOMP_VERSION_MOD"}
AOMP_MAJOR_VERSION=${AOMP_VERSION%.*}

# Set default value for ROCm install directory and the link directory.
# tr_build_aomp.sh will copy TheRock/build/dist/rocm to $AOMP_INSTALL_DIR
# and create a link from aomp to $AOMP_INSTALL_DIR.
# AOMP will be a symbolic link AOMP_INSTALL_DIR is the versioned dir name
AOMP=${AOMP:-$HOME/rocm/aomp}
AOMP_INSTALL_DIR=${AOMP}_${AOMP_VERSION_STRING}

# TR_AOMP_REPOS is the parent directory for TheRock and aomp repos.  
TR_AOMP_REPOS=${TR_AOMP_REPOS:-/work/$USER/git/tr_aomp}
if [ ! -d $TR_AOMP_REPOS ] ; then
  mkdir -p $TR_AOMP_REPOS
  [ $? != 0 ] && echo "ERROR: could not create $TR_AOMP_REPOS" && exit 1
fi

AOMP_INFO_FILE=$TR_AOMP_REPOS/aomp/tr_aomp/aomp_$AOMP_VERSION_STRING.info

# Set AOMP_BUILD_FROZEN_ROCK to 0 when AOMP build manager wants to start 
# new AOMP release. All developers use default 1 to clone and build AOMP
# using a frozen set of submodules except for llvm-project which builds
# with branch amd-staging. 
# Attention AOMP Build Manager: When building new AOMP release,  don't 
#                               forget to update new AOMP release above.
AOMP_BUILD_FROZEN_ROCK=${AOMP_BUILD_FROZEN_ROCK:-1} 
if [ $AOMP_BUILD_FROZEN_ROCK == 0 ] ; then 
   if [ -f $AOMP_INFO_FILE ] ; then 
      echo "ERROR: AOMP_BUILD_FROZEN_ROCK=0 BUT file $AOMP_INFO_FILE AREADY EXISTS"
      exit 1
   fi
   echo "ERROR: Support for AOMP_BUILD_FROZEN_ROCK==0 is not complete"
   echo "       In the future, this will be used to initialize AOMP release"
   exit 1
else
   if [ ! -f $AOMP_INFO_FILE ] ; then 
      echo "ERROR: AOMP_BUILD_FROZEN_ROCK=1 BUT file $AOMP_INFO_FILE DOES NOT EXIST"
      exit 1
   fi
fi

# to speedup build one can skip rccl build
AOMP_SKIP_RCCL=${AOMP_SKIP_RCCL:-0}
AOMP_SKIP_MATH_LIBS=${AOMP_SKIP_MATH_LIBS:-0}


export AOMP_VERSION_STRING AOMP_VERSION AOMP_VERSION_MOD AOMP_MAJOR_VERSION AOMP AOMP_INSTALL_DIR TR_AOMP_REPOS AOMP_BUILD_FROZEN_ROCK AOMP_SKIP_RCCL

