//#include "omp.h"
#include "stdio.h"

/** Problem is map clause tries to read value
 * from N from the device and write it into
 * constant memory (constant generated by LLVM)
 */
struct Bound_t{
  int bound;
  int dummy[8192];
};

struct Val_t {
  double dVal;
};

const struct Bound_t N = {.bound = 128, .dummy = {0}};
const struct Val_t A[128] = {0};
struct Val_t M;


int main(int argc, char **argv) {
  int tmp = 0;
  int tmp2 = 0;
  M.dVal = 1;

#pragma omp target teams distribute parallel for reduction(+:tmp) map(to:N) map(M)
  for (int i = 0; i < N.bound; i++) {
    tmp += 1;
    M.dVal = 42.0;
  }

  fprintf(stderr, "tmp: %u == 128\n", tmp);
  fprintf(stderr, "M: %.1f == 42.0\n", M.dVal);

  tmp = 0;

#pragma omp target teams distribute parallel for reduction(+:tmp) map(to: N) map(A) map(M)
  for (int i = 0; i < N.bound; i++) {
    tmp += A[i].dVal + 1;
    M.dVal = 42;
  }

  fprintf(stderr, "tmp: %u == 128\n", tmp);
  fprintf(stderr, "M: %.1f == 42\n", M.dVal);

#if 0

#pragma omp target teams distribute parallel for private(tmp) map(N) map(A)
  for (int i = 0; i < N; i++) {
    tmp += A[i];
    M = 42;
  }

#pragma omp target teams distribute parallel for private(tmp) map(tofrom:N) map(tofrom:A)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(to:N) map(to:M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(N, M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(N, M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }
#endif 

  fprintf(stderr, "Passed\n");

  return 0;
}
