//#include "omp.h"
#include "stdio.h"

/** Problem is map clause tries to read value
 * from N from the device and write it into
 * constant memory (constant generated by LLVM)
 */


#define ERROR_CHECK(value, expected) error = expected - value;\
                                           if (error) {\
                                             return error;\
                                           }
struct Bound_t{
  int bound;
  int dummy[8192];
};

struct Val_t {
  double dVal;
};

const struct Bound_t N = {.bound = 128, .dummy = {0}};
const struct Val_t A[128] = {0};
struct Val_t M;


int main(int argc, char **argv) {
  int tmp = 0;
  int error = 0;
  M.dVal = 1;

#pragma omp target teams distribute parallel for reduction(+:tmp) map(to:N) map(M)
  for (int i = 0; i < N.bound; i++) {
    tmp += 1;
    M.dVal = 42.0;
  }

  ERROR_CHECK(tmp, N.bound)
  ERROR_CHECK(M.dVal, 42.0)

  tmp = 0;

#pragma omp target teams distribute parallel for reduction(+:tmp) map(to: N) map(A) map(M)
  for (int i = 0; i < N.bound; i++) {
    tmp += A[i].dVal + 1;
    M.dVal = 42;
  }

  ERROR_CHECK(tmp, N.bound)
  ERROR_CHECK(M.dVal, 42)

  fprintf(stderr, "Passed\n");

  return 0;
}
