CXX = ${ROCM_PATH}/llvm/bin/clang++

CXXFLAGS += -O2 -fopenmp -target $(CLANG_HOST_TARGET) -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx908$(AOMP_TARGET_FEATURES)

LIBS = -lm -fopenmp -target $(CLANG_HOST_TARGET) -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx908$(AOMP_TARGET_FEATURES)

%.o:%.cc
	$(CXX) $(CXXFLAGS) -c $<
TARGET = ./main

all: $(TARGET)

OBJS = main.o f.o g.o

# dependencies
$(TARGET): $(OBJS)

$(TARGET): $(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

#------------------------------------------------------------------------------
#  Cleanup object files
clean :
	rm -rf *.o
	rm -f $(TARGET)

