include ../Makefile.defs

EXTRAFLAGS := -O3 -I/usr/local/cuda/include -lcudart

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
