include ../Makefile.defs

EXTRAFLAGS := -std=c++0x

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
