//#include "omp.h"
#include "stdio.h"

/** Problem is map clause tries to read value
 * from N from the device and write it into
 * constant memory (constant generated by LLVM)
 */
const int N = 128;
const int A[128] = {0};
int M = 1;


int main(int argc, char **argv) {
  int tmp = 0;
  int tmp2 = 0;

#pragma omp target teams distribute parallel for reduction(+:tmp) map(to:N) map(M)
  for (int i = 0; i < N; i++) {
    tmp += 1;
    M = 42;
  }

  fprintf(stderr, "tmp: %u == 128\n", tmp);
  fprintf(stderr, "M: %u == 42\n", M);

  tmp = 0;

#pragma omp target teams distribute parallel for reduction(+:tmp) map(to: N) map(A) map(M)
  for (int i = 0; i < N; i++) {
    tmp += A[i] + 1;
    M = 42;
  }

  fprintf(stderr, "tmp: %u == 128\n", tmp);
  fprintf(stderr, "M: %u == 42\n", M);

#if 0

#pragma omp target teams distribute parallel for private(tmp) map(N) map(A)
  for (int i = 0; i < N; i++) {
    tmp += A[i];
    M = 42;
  }

#pragma omp target teams distribute parallel for private(tmp) map(tofrom:N) map(tofrom:A)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(to:N) map(to:M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(N, M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(N, M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }
#endif 

  fprintf(stderr, "Passed\n");

  return 0;
}
