#include "omp.h"
#include "stdio.h"

/** Problem is map clause tries to read value
 * from N from the device and write it into
 * constant memory (constant generated by LLVM)
 */
const int N = 128;

int main(int argc, char **argv) {
  int tmp = 0;
#pragma omp target teams distribute parallel for private(tmp) map(N)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

  fprintf(stderr, "Passed\n");

  return 0;
}
