//#include "omp.h"
//#include "stdio.h"

/** Problem is map clause tries to read value
 * from N from the device and write it into
 * constant memory (constant generated by LLVM)
 */
const int N = 128;
int M = 1;

typedef struct A {
  int a;
} A_t;


int main(int argc, char **argv) {
  int tmp = 0;
  int tmp2 = 0;
  const int val = 42;
#pragma omp target teams distribute parallel for private(tmp) map(N)
  for (int i = 0; i < N; i++) {
    tmp += i;
    M = 42;
  }

#pragma omp target teams distribute parallel for private(tmp) map(N) map(M)
  for (int i = 0; i < N; i++) {
    tmp += i;
    M = 42;
  }

#pragma omp target teams distribute parallel for private(tmp) map(M) map(N)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(tofrom:N) map(tofrom:M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(to:N) map(to:M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(val) map(N, M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

#pragma omp target teams distribute parallel for private(tmp) map(val, N, M)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

  A_t a;
  const A_t b;
#pragma omp target teams distribute parallel for private(tmp) map(a) map(b.a) map(to:N)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

  const int *pVal = &val;
#pragma omp target teams distribute parallel for private(tmp) map(pVal) map(to:N)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

  const int *pTmp2 = &tmp2;
#pragma omp target teams distribute parallel for private(tmp) map(pTmp2[:1]) map(to:N)
  for (int i = 0; i < N; i++) {
    tmp += i;
    *pTmp2++;
  }
  
  const int *const pValConst = &val;
#pragma omp target teams distribute parallel for private(tmp) map(pValConst) map(to:N)
  for (int i = 0; i < N; i++) {
    tmp += i;
  }

  //fprintf(stderr, "Passed\n");

  return 0;
}
