include ../Makefile.defs

EXTRAFLAGS := #Some extra flags#

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
