include ../../Makefile.defs

TESTNAME     = clang-360537
TESTSRC_MAIN = clang-360537.cpp
TESTSRC_AUX  =
TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

CLANG        = clang++ -g

OMP_BIN      = $(AOMP)/bin/$(CLANG)
CC           = $(OMP_BIN) $(VERBOSE)
#-ccc-print-phases
#"-\#\#\#"

include ../Makefile.rules
run:
	ulimit -s unlimited ; ./$(TESTNAME)
