include ../../Makefile.defs

TESTNAME     = private_mapping
TESTSRC_MAIN = private_mapping.c
TESTSRC_AUX  =
TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

CLANG        = clang++

OMP_BIN	= $(AOMP)/bin/$(CLANG)
CC	= $(OMP_BIN)

include ../Makefile.rules
