!     ##################
      MODULE MODE_SNOW3L
!     ##################
INTERFACE SNOW3LSCAP
  MODULE PROCEDURE SNOW3LSCAP_1D
END INTERFACE

CONTAINS

FUNCTION SNOW3LSCAP_1D(PSNOWRHO) RESULT(PSCAP)
IMPLICIT NONE
REAL :: XCI
REAL :: JPRB
REAL, DIMENSION(:), INTENT(IN)                   :: PSNOWRHO
REAL, DIMENSION(SIZE(PSNOWRHO))                  :: PSCAP
PSCAP(:) = PSNOWRHO(:)*XCI      ! (J K-1 m-3)
END FUNCTION SNOW3LSCAP_1D

END MODULE MODE_SNOW3L
