MODULE MODE
  INTERFACE MYFUNC
    MODULE PROCEDURE MYFUNC_1D
  END INTERFACE

  CONTAINS

    FUNCTION MYFUNC_1D(INPUT) RESULT(OUTPUT)
      implicit none
      REAL, DIMENSION(:), INTENT(IN) :: INPUT
      REAL, DIMENSION(SIZE(INPUT))   :: OUTPUT
      OUTPUT(:) = INPUT(:)
    END FUNCTION MYFUNC_1D

END MODULE MODE

SUBROUTINE INIT(DATA)
  use MODE
  implicit none

  TYPE MYTYPE
    REAL, DIMENSION(:,:), POINTER :: W1
    REAL, DIMENSION(:,:), POINTER :: D1
    REAL, DIMENSION(:)  , POINTER :: RES
  END TYPE MYTYPE

  TYPE(MYTYPE),      INTENT(INOUT) :: DATA
  REAL, DIMENSION(1000) :: RES

  WHERE(DATA%W1(:,1)==0)
    RES(:)= 0
  ELSEWHERE
    RES(:) = DATA%D1(:,1) / MYFUNC(DATA%D1(:,1))
  END WHERE
END SUBROUTINE INIT
