include ../../Makefile.defs

TESTNAME     = global_allocate
TESTSRC_MAIN = global_allocate.c
TESTSRC_AUX  =
TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

CLANG        ?= clang
OMP_BIN      = $(AOMP)/bin/$(CLANG)
CC           = $(OMP_BIN) $(VERBOSE)

UNSUPPORTED = ASAN_RUNTIME

include ../Makefile.rules
