#include ../../Makefile.defs

#TESTNAME     = offload
#TESTSRC_MAIN = offload.c
#TESTSRC_AUX  =
#TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

#CLANG        = clang
#OMP_BIN      = $(AOMP)/bin/$(CLANG)
#CC           = $(OMP_BIN) $(VERBOSE)

#include ../Makefile.rules
run:
	./doit.sh 
