#!/bin/bash
#  get_trunk_pr_patches: 
#     get_trunk_pr_patches takes a single argument which is the page number
#     of all the pull request pages. The default is 1 which is the lastest PRs.
#     Each page is 25 pull requests.  This script only gets a single page.  
#     However, All patches remaining in $tdir are dry-run tested. 

page_num=${1:-1}

# --- Start standard header ----
realpath=`realpath $0`
thisdir=`dirname $realpath`
. $thisdir/trunk_common_vars
# --- end standard header ----

curdir=$PWD
tdir="/tmp/$USER/trunk_patches"
mkdir -p $tdir
cd $tdir

rm -f pull_page_$page_num
wget https://github.com/llvm/llvm-project/pulls?page=$page_num -O pull_page_$page_num 2>/dev/null >/dev/null
cat pull_page_$page_num | grep llvm/llvm-project/pull | grep pull_request | cut -d"/" -f7- | cut -d"<" -f1 |  while read line ; do 
     dir=`echo $line | cut -d"\"" -f1`
     comment=`echo $line | cut -d">" -f2`
     number=`echo $dir | cut -d"/" -f4`
     patchurl="https://github.com/${dir}.patch"
     local_file=${patchurl##*/}
     [ -f $local_file ] && rm -f $local_file 
     echo wget $patchurl -O $local_file 
     wget $patchurl 2>/dev/null >/dev/null

     cfile=comment.${number}.txt
     echo $comment > $cfile
done
echo
echo " DONE getting files into $tdir"

echo " Now attempting to dry-run patches to $TRUNK_REPOS/$LLVMPROJECT"
echo

cd $TRUNK_REPOS/$LLVMPROJECT
for patchfile in `ls $tdir/*.patch` ; do 
  lines=`wc -l $patchfile | cut -d" " -f1`
  number=`echo $patchfile | cut -d"." -f1 | cut -d"/" -f5`
  comment=`cat $tdir/comment.${number}.txt`
  patch -p1 -t -N --dry-run <$patchfile >/dev/null
  if [ $? != 0 ] ; then
     echo "FAIL ${number}.patch  title: \"$comment\" $lines lines, try:"
     echo "   patch -p1 -t -N --dry-run <$patchfile"
    #  patch -p1 -t -N --dry-run <$patchfile 
  else
     echo "OK   ${number}.patch  title: \"$comment\" $lines lines"
 #  echo "patch -p1 --no-backup-if-mismatch \<patchfile"
  fi
done
echo
echo " See above patches in directory $tdir"
echo
cd $curdir

