include ../Makefile.defs

EXTRAFLAGS := -O0 -fopenmp-implicit-declare-target

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
