include ../Makefile.defs

EXTRAFLAGS := -O3 --cuda-noopt-device-debug

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
