include ../Makefile.defs

EXTRAFLAGS := -O0 -lm

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
