include ../Makefile.defs

EXTRAFLAGS := -O0 -fopenmp-ignore-unmappable-types

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
