include ../../Makefile.defs

TESTNAME     = clang-341190
TESTSRC_MAIN = clang-341190.c
TESTSRC_AUX  =
TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

CLANG        = clang
OMP_FLAGS	+=  -DSPEC_OMP_TARGET 

OMP_BIN      = $(AOMP)/bin/$(CLANG)
CC           = $(OMP_BIN) $(VERBOSE)
#-ccc-print-phases
#"-\#\#\#"

include ../Makefile.rules

