#!/bin/bash
#
#Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
#SPDX-License-Identifier:  MIT
# 
#  srock_common_vars: This file is sourced by srock scripts to set
#                     set common SROCK environment variables.
#
#  The bash syntax ENVNAME=${ENVNAME:-value} checks if ENVNAME is
#  already set. If not, it assigns it the value following the :-
#  So, if you preset any SROCK env vars such as in .bashrc, 
#  you override the default specified here. Most importantly, 
#  You should set SROCK_REPOS to an updateable high performance and
#  large capacity (100GB+) directory 100GB+

function test_apply_patch() {
   # shellcheck disable=SC2154 # $_patch_file &_curdir are set externally
   if ! patch -p1 -t -N --merge --dry-run < "$_patch_file"  >/dev/null; then
      echo "ERROR:  patch --dry-run failed.  Could not apply $_patch_file "
      cd "$_curdir" || exit 1
      exit 1
   else
      echo "patch -p1 --no-backup-if-mismatch --merge < $_patch_file"
      patch -p1 --no-backup-if-mismatch --merge < "$_patch_file"
   fi
}

function srock_venv_activate() {
    if [ -d "$SROCK_THEROCK_DIR/$SROCK_VENV/bin" ] ; then
       echo
       echo "===== Activating virtual environment ====="
       cd "$SROCK_THEROCK_DIR" || exit
       echo "source $SROCK_VENV/bin/activate"
       # shellcheck disable=SC1091 # don't analyze activate
       source "$SROCK_VENV/bin/activate"
    else
       echo
       echo "===== Building virtual environment in $SROCK_VENV and updating PATH ====="
       cd "$SROCK_THEROCK_DIR" || exit
       echo "python3 -m venv $SROCK_VENV && source $SROCK_VENV/bin/activate"
       # shellcheck disable=SC1091 # don't analyze activate
       python3 -m venv "$SROCK_VENV" && source "$SROCK_VENV/bin/activate"
    fi
    echo "pip install -r requirements.txt"
    pip install -r requirements.txt
    export PATH=$SROCK_THEROCK_DIR/$SROCK_VENV/bin:$PATH
}

function chk_cmake() {
    if [ "$_build_cmake" == 1 ] && [ -f "$_cmake_local" ] ; then
       _cmake_ver=$($_cmake_local --version 2>/dev/null | grep version | cut -d" " -f3)
       if [ "$_cmake_ver" != "" ] ; then
           _cmake_major=${_cmake_ver%%.*}
           _cmake_rel=$(echo "$_cmake_ver" | cut -d"." -f2)
           _cmake_dir=$(dirname "$_cmake_local")
           if ((  ( _cmake_major >= 4 ) ||
                 (( _cmake_major == 3 ) && ( _cmake_rel >= 25 )) )); then
              _build_cmake=0
              export PATH="$_cmake_dir:$PATH"
              # echo "      $_cmake_local cmake is ok"
              SROCK_CMAKE=$_cmake_local
           fi
       fi
    fi
}

# shellcheck disable=SC2034 # currently unused
SROCK="NEVER_USE_'\$SROCK'_ENV_VARIABLE" # Use SROCK_LINK

#  SROCK_REPOS is the parent directory for TheRock and srock repos.  
SROCK_REPOS=${SROCK_REPOS:-${HOME}/git/srock-repos}
if [ ! -d "$SROCK_REPOS" ] ; then
  if ! mkdir -p "$SROCK_REPOS"; then
      echo "ERROR: Could not create $SROCK_REPOS"
      exit 1
  fi
fi

SROCK_VERSION=${SROCK_VERSION:-"7.13"}
SROCK_VERSION_MOD=${SROCK_VERSION_MOD:-"0"}
SROCK_VERSION_STRING=${SROCK_VERSION_STRING:-"$SROCK_VERSION-$SROCK_VERSION_MOD"}
SROCK_MAJOR_VERSION=${SROCK_VERSION%.*}

# Set SROCK_COMPILER_BRANCH to develop to get a native TheRock build
SROCK_COMPILER_BRANCH=${SROCK_COMPILER_BRANCH:-amd-staging}
#SROCK_THEROCK_BRANCH=${SROCK_THEROCK_BRANCH:-compiler/amd-staging}
SROCK_THEROCK_BRANCH=${SROCK_THEROCK_BRANCH:-main}
SROCK_CONFIG=${SROCK_CONFIG:-minimal}

# Set default value for ROCm install directory SROCK_INSTALL_DIR.
# Unlike aomp, which installs each component after build, build_srock.sh
# will install into $SROCK_INSTALL_DIR only after a fully successful
# build of all TheRock configured components.  It will then create  
# a symbolic link from $SROCK to the versioned name $SROCK_INSTALL_DIR.
SROCK_LINK=${SROCK_LINK:-$HOME/rocm/srock}
SROCK_INSTALL_DIR=${SROCK_LINK}_${SROCK_VERSION_STRING}

SROCK_THEROCK_DIR=$SROCK_REPOS/TheRock
SROCK_VENV=${SROCK_VENV:-.venv}

export SROCK_REPOS SROCK_VERSION_STRING SROCK_VERSION SROCK_VERSION_MOD SROCK_MAJOR_VERSION SROCK_LINK SROCK_INSTALL_DIR SROCK_THEROCK_DIR

SROCK_REPO_NAME=${SROCK_REPO_NAME:-aomp}
# These local variables are only used during build to log important information.
SROCK_VERSION_INFO_DIR=$SROCK_REPOS/$SROCK_REPO_NAME/srock-bin/srock_$SROCK_VERSION_STRING
# shellcheck disable=SC2034 # currently unused
SROCK_INFO_FILE=$SROCK_VERSION_INFO_DIR/srock_$SROCK_VERSION_STRING.info
# shellcheck disable=SC2034 # currently unused
SROCK_SUBMOD_FILE=$SROCK_VERSION_INFO_DIR/srock_$SROCK_VERSION_STRING.submodules

# SROCK_SUPP is for SUPPlemental software components needed for testing.
# such as openmpi, hdf5, and silo. Applications that need supplemental
# components can get the latest version with $SROCK_SUPP/<component name>
SROCK_SUPP=${SROCK_SUPP:-$HOME/local}
# SROCK_SUPP_BUILD could be a temp directory but defaults to $SROCK_SUPP/build
SROCK_SUPP_BUILD=${SROCK_SUPP_BUILD:-$SROCK_SUPP/build}
# SROCK_SUPP_INSTALL must be permanent directory.
SROCK_SUPP_INSTALL=${SROCK_SUPP_INSTALL:-$SROCK_SUPP/install}
export SROCK_SUPP SROCK_SUPP_BUILD SROCK_SUPP_INSTALL
export PATH=$SROCK_SUPP/ninja/bin:$PATH

# Specify target GFXLIST/GFXFAM
# gfx not currently supported by TheRock:
#   gfx900 gfx902 gfx90c gfx1031 gfx1052 gfx1053
#   gfx9-generic gfx9-4-generic gfx10-1-generic gfx10-3-generic gfx11-generic gfx12-generic
GFXLIST=${GFXLIST:-"gfx906 gfx908 gfx90a gfx942 gfx950 gfx1010 gfx1011 gfx1012 gfx1030 gfx1032 gfx1035 gfx1036 gfx1100 gfx1101 gfx1102 gfx1103 gfx1150 gfx1151 gfx1200 gfx1201"}
export GFXLIST
GFXFAM=${GFXFAM:-"dcgpu-all dgpu-all igpu-all"}
export GFXFAM

# Calculate the number of threads to use for make
COMP_THREADS=1
if [ "$(which getconf)" ] && [ "$(which bc)" ]; then
    COMP_THREADS=$(getconf _NPROCESSORS_ONLN)
    COMP_THREADS=$(echo "$COMP_THREADS/2.5" | bc)
fi
SROCK_JOB_THREADS=${SROCK_JOB_THREADS:-$COMP_THREADS}
NINJA_NPROCS=${NINJA_NPROCS:-$SROCK_JOB_THREADS}
export SROCK_JOB_THREADS NINJA_NPROCS

SROCK_DEV_BRANCH=${SROCK_DEV_BRANCH:-aomp-dev}
SROCK_HIPFORT_BRANCH=${SROCK_HIPFORT_BRANCH:-release/rocm-rel-7.2}
SROCK_ROCGDB_BRANCH=${SROCK_ROCGDB_BRANCH:-release/rocm-rel-7.2}
SROCK_ROCDBGAPI_BRANCH=${SROCK_ROCDBGAPI_BRANCH:-release/rocm-rel-7.2}

_build_cmake=1
SROCK_CMAKE=$(which cmake)
_cmake_local=$SROCK_CMAKE
chk_cmake

# Check the local build of cmake
_cmake_local=$SROCK_SUPP/cmake/bin/cmake
chk_cmake

if [ $_build_cmake == 1 ] ; then
   export PATH=$SROCK_SUPP/cmake/bin:$PATH
   SROCK_CMAKE=$_cmake_local
fi
export SROCK_CMAKE

# TWO QUICK CHECKS, MUST HAVE SROCK_REPOS and SROCK_THEROCK_DIR MUST NOT EXIST
mkdir -p "$SROCK_REPOS"
if [ ! -d "$SROCK_REPOS" ] ; then
   echo
   echo "ERROR: $0 could not create directory $SROCK_REPOS"
   echo "       Consider setting SROCK_REPOS to use a large fast fileystem."
   echo "       or $HOME/git/srock-repos"
   echo
   exit 1
fi

declare -a _cmake_enable
_cmake_enable=()

# This TheRock config is full build minus failing components
if [ "$SROCK_CONFIG" == "all" ] ; then
   _cmake_enable=("${_cmake_enable[@]}"
      -DTHEROCK_ENABLE_ALL=ON
      -DTHEROCK_ENABLE_MIOPEN=OFF
      -DTHEROCK_ENABLE_COMPOSABLE_KERNEL=OFF
      -DTHEROCK_ENABLE_FFT=OFF
   )
fi

# This is full build which could include failing components
if [ "$SROCK_CONFIG" == "all-debug" ] ; then
   _cmake_enable=("${_cmake_enable[@]}"
	   -DTHEROCK_ENABLE_ALL=ON )
fi

# Default is minimal for compiler developers
if [ "$SROCK_CONFIG" == "minimal" ] ; then
   _cmake_enable=("${_cmake_enable[@]}"
      -DTHEROCK_ENABLE_ALL=OFF
      -DTHEROCK_ENABLE_HIP_RUNTIME=ON
      -DTHEROCK_ENABLE_HIPIFY=ON
      -DTHEROCK_BUNDLE_SYSDEPS=ON
      -DTHEROCK_ENABLE_COMPILER=ON
      -DTHEROCK_ENABLE_AMD_DBGAPI=ON
      -DTHEROCK_ENABLE_OCL_RUNTIME=ON
      -DTHEROCK_ENABLE_ROCGDB=ON
   )
fi

_gfxsemicolons=$(echo "$GFXLIST" | tr ' ' ';')
_gfamsemicolons=$(echo "$GFXFAM" | tr ' ' ';')

declare -a _cmake_args
# shellcheck disable=SC2206 # word splitting intended on $SROCK_CMAKE_EXTRA
_cmake_args=(-B build -GNinja
   -DCMAKE_INSTALL_PREFIX="$SROCK_INSTALL_DIR"
   -DTHEROCK_AMDGPU_TARGETS=\'"$_gfxsemicolons"\'
   -DTHEROCK_AMDGPU_FAMILIES=\'"$_gfamsemicolons"\'
   -DTHEROCK_AMDGPU_DIST_BUNDLE_NAME=srock
   -DTHEROCK_BACKGROUND_BUILD_JOBS=1
   -DTHEROCK_BUILD_LLVM_TESTS=1
   "${_cmake_enable[@]}"
   $SROCK_CMAKE_EXTRA
   "$SROCK_THEROCK_DIR"
)

