include ../../Makefile.defs

TESTNAME     = gpurun-tests
TESTSRC_MAIN = gpurun-tests.c
TESTSRC_AUX  =
TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

#-ccc-print-phases
#"-\#\#\#"

RUNCMD       = ./chkit.sh ${TESTNAME}

include ../Makefile.rules
