#!/bin/bash
bldcmd="$AOMP/bin/hipcc -g -O2 -fopenmp matrixmul.cpp -o matrixmul"
gdbcmd="$AOMP/bin/rocgdb --data-directory=$AOMP/share/gdb -x $AOMP/lib-debug/ompd/__init__.py -- ./matrixmul "
cgdb=`which cgdb` && [ "$cgdb" != "" ] && gdbcmd="$cgdb -d $gdbcmd"

export LD_LIBRARY_PATH=$AOMP/lib-debug:$AOMP/lib
export OMP_DEBUG=enabled

echo
echo $bldcmd
$bldcmd
echo
echo $gdbcmd
echo
$gdbcmd


