include ../../Makefile.defs

TESTNAME     = clang-408351
TESTSRC_MAIN = clang-408351.c
TESTSRC_AUX  =
TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

CLANG        = amdclang
OMP_BIN      = $(AOMP)/bin/$(CLANG)
#-ccc-print-phases
#"-\#\#\#"

include ../Makefile.rules

