#-----------------------------------------------------------------------
#
#  Makefile.find_gpu_and_install_dir
#     Include for examples to find LLVM installation and GPU arch.
#     This include sets LLVM_INSTALL_DIR, LLVM_GPU_TRIPLE, and LLVM_GPU_ARCH
#     This include also sets CUDA and LFLAGS to find CUDA lib if NVIDIA gpu
#
# If LLVM_INSTALL_DIR not preset and AOMP is, then use AOMP and print deprication warning
ifeq ("$(wildcard $(LLVM_INSTALL_DIR))","")
ifneq ("$(wildcard $(AOMP))","")
  $(info 'WARNING: Environment variable AOMP deprecated for examples.')
  $(info '         Please set LLVM_INSTALL_DIR to avoid this message.')
  LLVM_INSTALL_DIR = $(AOMP)
  $(info '         Using $(LLVM_INSTALL_DIR) for LLVM_INSTALL_DIR.')
endif
endif

# If LLVM_INSTALL_DIR not preset, seach private build, rocm, and then installed aomp
ifeq ("$(wildcard $(LLVM_INSTALL_DIR))","")
  ifneq ($(LLVM_INSTALL_DIR),)
    $(warning Specified LLVM_INSTALL_DIR:$(LLVM_INSTALL_DIR) NOT FOUND)
  endif
  dirs := $(HOME)/rocm/aomp /opt/rocm/llvm /usr/lib/aomp
  # Select the first directory found from above list.
  LLVM_INSTALL_DIR := $(word 1, $(strip $(foreach dir,$(dirs),$(wildcard $(dir)))))
  ifeq ("$(wildcard $(LLVM_INSTALL_DIR))","")
    $(error Please install ROCm, AOMP, or set LLVM_INSTALL_DIR to LLVM install dir)
  endif
  ### $(info Set LLVM_INSTALL_DIR = $(LLVM_INSTALL_DIR))
endif

# Test for GPUs and get offload arch from either nvidia-arch or amdgpu-arch
_amdgpu_mod_dir = $(shell ls -d /sys/module/amdgpu 2>/dev/null)
ifeq ("$(wildcard $(_amdgpu_mod_dir))","")
   _nvidia_pcidev = $(shell lspci -nd 10de:*:*)
   ifeq ($(_nvidia_pcidev),)
     $(error NO amdgpu or nvidia GPU detected)
   endif	
   LLVM_GPU_TRIPLE = nvptx64-nvidia-cuda
   LLVM_GPU_ARCH   = $(shell $(LLVM_INSTALL_DIR)/bin/nvidia-arch | head -n 1 )
   UNAMEP          = $(shell uname -m)
   CUDA           ?= /usr/local/cuda
   LFLAGS         += -L$(CUDA)/targets/$(UNAMEP)-linux/lib -lcudart
else
   LLVM_GPU_TRIPLE = amdgcn-amd-amdhsa
   LLVM_GPU_ARCH   = $(shell $(LLVM_INSTALL_DIR)/bin/amdgpu-arch | head -n 1 )
endif

###$(info Set LLVM_GPU_TRIPLE  = $(LLVM_GPU_TRIPLE)) 
###$(info Set LLVM_GPU_ARCH    = $(LLVM_GPU_ARCH))
