include ../Makefile.defs

EXTRAFLAGS := -O0 -std=c++11

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
