include ../Makefile.defs

EXTRAFLAGS := -O3

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################
#export OMP_NUM_TEAMS=32
include ../Makefile.rules
