include ../../Makefile.defs
#TESTNAME     = flang-357267
#TESTSRC_MAIN = flang-357267.f90
#TESTSRC_AUX  =
#TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

#-ccc-print-phases
#"-\#\#\#"
#include ../Makefile.rules

run:
	./doit
