include ../../Makefile.defs

TESTNAME     = issue2080
TESTSRC_MAIN = issue2080.c
#TESTSRC_AUX  =
TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

#CLANG        = clang
#CFLAGS       =
#OMP_BIN      = $(AOMP)/bin/$(CLANG)
#CC           = $(OMP_BIN) $(VERBOSE)

include ../Makefile.rules
