include ../../Makefile.defs

TESTNAME     = kmpc_alloc
TESTSRC_MAIN = kmpc_alloc.cpp
TESTSRC_AUX  =
TESTSRC_ALL  = $(TESTSRC_MAIN) $(TESTSRC_AUX)

CLANG        ?= clang++
OMP_BIN      = $(AOMP)/bin/$(CLANG)
CC           = $(OMP_BIN) $(VERBOSE)

UNSUPPORTED = ASAN_RUNTIME

include ../Makefile.rules
