name: AOMP Lint

on:
  push:
  pull_request:

jobs:
  aomp-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run shellcheck
        run: |
          find . -name "*.sh" -exec shellcheck -S info {} +
