name: AOMP shellcheck lint

on:
  pull_request:

jobs:
  aomp-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323
        with:
          separator: ' '
          skip_initial_fetch: true
          base_sha: 'HEAD~1'
          sha: 'HEAD'

      - name: Echo changed files
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Run shellcheck
        run: |
          shellcheck_status=0
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.sh ]]; then
              file_dir=$(dirname "$file")
              file_name=$(basename "$file")

              echo "Running shellcheck on $file in directory $file_dir"
              pushd "$file_dir"

              shellcheck -x "$file_name"
              if [ $? -ne 0 ]; then
                shellcheck_status=1
              fi

              popd
            fi
          done
          exit $shellcheck_status
        shell: bash {0}
